import { CommonModule } from '@angular/common';
import { ChangeDetectorRef, Component, OnInit, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { ClientApiService, Hotel, PromotionQuote, RoomType } from '../../../core/services/client-api.service';
import { ImageFallbackService } from '../../../core/services/image-fallback.service';
import { PublicI18nService } from '../../../core/i18n/public-i18n.service';
import { FavoriteButtonComponent } from '../favorites/favorite-button.component';

@Component({selector:'app-hotel-detail',standalone:true,imports:[CommonModule,FormsModule,FavoriteButtonComponent],templateUrl:'./hotel-detail.component.html',styleUrls:['./hotel-detail.component.css']})
export class HotelDetailComponent implements OnInit {
  private readonly route=inject(ActivatedRoute); private readonly router=inject(Router); private readonly api=inject(ClientApiService); private readonly changeDetector=inject(ChangeDetectorRef); readonly fallback=inject(ImageFallbackService); readonly i18n=inject(PublicI18nService);
  hotel:Hotel|null=null; roomTypes:RoomType[]=[]; isLoading=true; pageError=''; roomError=''; selectedRoomType:RoomType|null=null; selectedQuantity=0; selectedQuote:PromotionQuote|null=null; quoteLoading=false; quoteError=''; hotelId=0; private quoteRequestToken=0;
  bookingQueryParams:{checkIn?:string;checkOut?:string;adultCount:number;childCount:number;roomCount:number}={adultCount:2,childCount:0,roomCount:1};
  showClaimModal=false; claimForm={verificationMethod:'BUSINESS_LICENSE',verificationData:'',note:''};
  ngOnInit():void{this.route.queryParams.subscribe(p=>{this.bookingQueryParams={checkIn:p['checkInDate']||p['checkIn'],checkOut:p['checkOutDate']||p['checkOut'],adultCount:Number(p['adultCount'])||Number(p['guests'])||2,childCount:Number(p['childCount'])||0,roomCount:Number(p['roomCount'])||1};if(this.hotel?.id)this.loadRoomTypes(this.hotel.id);});this.route.paramMap.subscribe(p=>{const id=Number(p.get('id'));if(!Number.isInteger(id)||id<=0){this.showPageError(this.i18n.text('PUBLIC.DETAIL.INVALID_ROUTE'));return;}this.hotelId=id;this.loadHotelData(id);});}
  get guests():number{return this.bookingQueryParams.adultCount+this.bookingQueryParams.childCount;} get nights():number{if(!this.bookingQueryParams.checkIn||!this.bookingQueryParams.checkOut)return 1;return Math.max(1,Math.round((new Date(this.bookingQueryParams.checkOut).getTime()-new Date(this.bookingQueryParams.checkIn).getTime())/86400000));}
  get roomRequirement():string{const checkIn=this.bookingQueryParams.checkIn||this.i18n.text('PUBLIC.DATES.NOT_SELECTED');const checkOut=this.bookingQueryParams.checkOut||this.i18n.text('PUBLIC.DATES.NOT_SELECTED');return `${checkIn} - ${checkOut} · ${this.i18n.count('PUBLIC.DETAIL.GUEST_COUNT',this.guests)} · ${this.i18n.count('PUBLIC.DETAIL.ROOM_NEEDED',this.bookingQueryParams.roomCount)}`;}
  get roomSubtotal():number{return this.selectedQuote?.baseSubtotal??0;} get roomTotal():number{return this.selectedQuote?.finalTotal??0;} get roomTax():number{return this.selectedQuote?.taxesAndFees??0;} get canContinue():boolean{return !!this.selectedRoomType&&this.selectedQuantity>0&&this.selectedQuantity<=this.maxQuantity(this.selectedRoomType)&&this.capacityValid&&(!this.bookingQueryParams.checkIn||!!this.selectedQuote)&&!this.quoteLoading;}
  get promotionNames():string{return (this.selectedQuote?.appliedPromotions??[]).map(p=>this.i18n.dateLocale()==='en-US'?(p.nameEn||p.nameVi):p.nameVi).join(', ');}
  get memberTierLabel():string{const benefit=this.selectedQuote?.memberBenefit;if(!benefit?.eligible)return '';return this.i18n.dateLocale()==='en-US'?(benefit.tierNameEn||benefit.tierNameVi||''):(benefit.tierNameVi||benefit.tierNameEn||'');}
  get sponsoredDisclosure():string{const placement=this.hotel?.sponsoredPlacement;return placement?(this.i18n.dateLocale()==='en-US'?placement.disclosureEn:placement.disclosureVi):'';}
  get capacityValid():boolean{if(!this.selectedRoomType||!this.selectedQuantity)return false;const maxA=this.selectedRoomType.maxAdults??this.selectedRoomType.maxGuests??this.selectedRoomType.maxGuest;const maxC=this.selectedRoomType.maxChildren??this.selectedRoomType.maxGuests??this.selectedRoomType.maxGuest;const maxG=this.selectedRoomType.maxGuests??this.selectedRoomType.maxGuest;return this.bookingQueryParams.adultCount<=maxA*this.selectedQuantity&&this.bookingQueryParams.childCount<=maxC*this.selectedQuantity&&this.guests<=maxG*this.selectedQuantity;}
  loadHotelData(id:number):void{this.isLoading=true;this.pageError='';this.roomError='';this.hotel=null;this.api.getHotelById(id).subscribe({next:h=>{if(!h){this.showPageError(this.i18n.text('PUBLIC.DETAIL.NOT_FOUND'));return;}this.hotel=h;this.changeDetector.detectChanges();this.loadRoomTypes(id);},error:error=>{this.showPageError(error?.status===404?this.i18n.text('PUBLIC.DETAIL.NOT_FOUND'):this.i18n.text('PUBLIC.DETAIL.LOAD_PROPERTY_ERROR'));}});}
  loadRoomTypes(id:number):void{this.roomError='';this.api.getRoomTypesByHotel(id,this.bookingQueryParams.checkIn,this.bookingQueryParams.checkOut,this.guests).subscribe({next:r=>{this.roomTypes=r;this.selectedRoomType=null;this.selectedQuantity=0;this.selectedQuote=null;this.quoteError='';this.isLoading=false;this.changeDetector.detectChanges();setTimeout(()=>{if(this.route.snapshot.fragment==='rooms')this.scrollToRooms();});},error:error=>{if(error?.status===404){this.showPageError(this.i18n.text('PUBLIC.DETAIL.NOT_FOUND'));return;}this.roomTypes=[];this.roomError=this.i18n.text('PUBLIC.DETAIL.LOAD_ERROR');this.isLoading=false;this.changeDetector.detectChanges();}});}
  selectQuantity(room:RoomType,value:number):void{const quantity=Math.max(0,Math.min(this.maxQuantity(room),Number(value)||0));if(quantity===0){if(this.selectedRoomType?.id===room.id){this.selectedRoomType=null;this.selectedQuantity=0;this.selectedQuote=null;}return;}this.selectedRoomType=room;this.selectedQuantity=quantity;this.loadSelectedQuote();}
  private loadSelectedQuote():void{const propertyId=this.hotel?.id||this.hotelId;const checkIn=this.bookingQueryParams.checkIn;const checkOut=this.bookingQueryParams.checkOut;this.selectedQuote=null;this.quoteError='';if(!propertyId||!this.selectedRoomType||!checkIn||!checkOut){return;}const token=++this.quoteRequestToken;this.quoteLoading=true;this.api.getPromotionQuote({propertyId,roomTypeId:this.selectedRoomType.id,checkInDate:checkIn,checkOutDate:checkOut,quantity:this.selectedQuantity,adultCount:this.bookingQueryParams.adultCount,childCount:this.bookingQueryParams.childCount}).subscribe({next:quote=>{if(token!==this.quoteRequestToken)return;this.selectedQuote=quote;this.quoteLoading=false;this.changeDetector.detectChanges();},error:()=>{if(token!==this.quoteRequestToken)return;this.quoteLoading=false;this.quoteError=this.i18n.text('PUBLIC.DETAIL.LOAD_ERROR');this.changeDetector.detectChanges();}});}
  maxQuantity(room:RoomType):number{return Math.max(0,Math.min(room.availableRooms??0,this.bookingQueryParams.roomCount));} quantities(room:RoomType):number[]{return Array.from({length:this.maxQuantity(room)+1},(_,i)=>i);}
  continueBooking():void{if(!this.canContinue||!this.selectedRoomType||!this.hotel)return;this.router.navigate(['/booking',this.selectedRoomType.id],{queryParams:{checkIn:this.bookingQueryParams.checkIn,checkOut:this.bookingQueryParams.checkOut,adultCount:this.bookingQueryParams.adultCount,childCount:this.bookingQueryParams.childCount,roomCount:this.bookingQueryParams.roomCount,quantity:this.selectedQuantity,hotelId:this.hotel.id,roomTypeName:this.selectedRoomType.nameVi,nightlyPrice:this.selectedQuote?.nightlyPrice,estimatedTotal:this.selectedQuote?.finalTotal,quoteId:this.selectedQuote?.quoteId}});}
  roomImage(room:RoomType):string{return room.imageUrls?.[0]||this.fallback.room(room.code);} handleRoomImageError(e:Event,room:RoomType):void{this.fallback.replace(e,this.fallback.room(room.code));} handleHotelImageError(e:Event):void{this.fallback.replace(e,this.fallback.property(this.hotel?.propertyType));}
  bedLabel(value?:string):string{const key=({SINGLE:'BED_SINGLE',DOUBLE:'BED_DOUBLE',TWIN:'BED_TWIN',MULTIPLE:'BED_MULTIPLE'} as Record<string,string>)[value||''];return key?this.i18n.text(`PUBLIC.DETAIL.${key}`):value||this.i18n.text('PUBLIC.DETAIL.BED_DEFAULT');}
  formatVnd(value:number):string{return `${new Intl.NumberFormat('vi-VN',{maximumFractionDigits:0}).format(value||0)} ₫`;}
  scrollToRooms():void{document.getElementById('rooms')?.scrollIntoView({behavior:'smooth'});} submitClaim():void{if(!this.hotel)return;this.api.submitPropertyClaim(this.hotel.id,this.claimForm).subscribe({next:()=>{this.showClaimModal=false;alert(this.i18n.text('PUBLIC.DETAIL.CLAIM_SENT'));},error:()=>alert(this.i18n.text('PUBLIC.DETAIL.CLAIM_FAILED'))});}
  retry():void{if(this.hotelId>0)this.loadHotelData(this.hotelId);}
  browseProperties():void{this.router.navigate(['/search']);}
  private showPageError(message:string):void{this.hotel=null;this.roomTypes=[];this.selectedRoomType=null;this.selectedQuantity=0;this.selectedQuote=null;this.quoteLoading=false;this.pageError=message;this.isLoading=false;this.changeDetector.detectChanges();}
}
