/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  corePlugins: {
    preflight: false, // Important: disable preflight to prevent breaking PrimeNG/Bootstrap
  },
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#261900",
        "on-tertiary-container": "#898b8c",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "secondary": "#775a19",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#d1e4fb",
        "surface-container-highest": "#d1e4fb",
        "on-surface": "#091d2d",
        "background": "#f7f9ff",
        "on-background": "#091d2d",
        "tertiary-fixed": "#e1e3e4",
        "primary-fixed": "#d2e4ff",
        "inverse-on-surface": "#e8f2ff",
        "surface-dim": "#c9dcf2",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#5d4201",
        "error": "#ba1a1a",
        "primary": "#000f22",
        "surface": "#f7f9ff",
        "tertiary-fixed-dim": "#c5c7c8",
        "on-error": "#ffffff",
        "on-surface-variant": "#43474d",
        "outline-variant": "#c4c6ce",
        "outline": "#74777e",
        "on-tertiary-fixed-variant": "#454748",
        "inverse-primary": "#b0c8eb",
        "on-tertiary-fixed": "#191c1d",
        "primary-container": "#0a2540",
        "on-primary-fixed": "#001c37",
        "error-container": "#ffdad6",
        "on-secondary-container": "#785a1a",
        "on-primary-fixed-variant": "#314865",
        "inverse-surface": "#203243",
        "secondary-fixed": "#ffdea5",
        "surface-container-low": "#edf4ff",
        "surface-container-high": "#d8eaff",
        "surface-container": "#e3efff",
        "secondary-container": "#fed488",
        "surface-tint": "#49607e",
        "tertiary": "#0c0f10",
        "secondary-fixed-dim": "#e9c176",
        "on-primary-container": "#768dad",
        "surface-bright": "#f7f9ff",
        "tertiary-container": "#212425",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#b0c8eb"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "24px",
        "stack-sm": "12px",
        "margin-mobile": "16px",
        "unit": "8px",
        "stack-lg": "48px",
        "stack-md": "24px",
        "container-max": "1440px",
        "stack-xs": "4px",
        "margin-desktop": "40px"
      },
      fontFamily: {
        "headline-lg": ["Source Serif 4", "serif"],
        "display-lg": ["Source Serif 4", "serif"],
        "label-md": ["Hanken Grotesk", "sans-serif"],
        "body-sm": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Source Serif 4", "serif"],
        "headline-md": ["Source Serif 4", "serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
