CREATE TABLE dbo.staff_booking_quotes (
    id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    public_id VARCHAR(36) NOT NULL,
    hotel_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    room_type_id BIGINT NOT NULL,
    check_in_date DATE NOT NULL,
    check_out_date DATE NOT NULL,
    quantity INT NOT NULL,
    adults INT NOT NULL,
    children INT NOT NULL,
    payment_method VARCHAR(40) NOT NULL,
    special_requests NVARCHAR(1000) NULL,
    base_price DECIMAL(19,0) NOT NULL,
    total_amount DECIMAL(19,0) NOT NULL,
    deposit_amount DECIMAL(19,0) NOT NULL,
    payment_config_id BIGINT NOT NULL,
    payment_config_version BIGINT NOT NULL,
    available_rooms BIGINT NOT NULL,
    expires_at DATETIME2 NOT NULL,
    status VARCHAR(20) NOT NULL,
    reservation_id BIGINT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_staff_booking_quotes_public_id UNIQUE(public_id),
    CONSTRAINT fk_staff_quote_hotel FOREIGN KEY(hotel_id) REFERENCES dbo.hotels(id),
    CONSTRAINT fk_staff_quote_customer FOREIGN KEY(customer_id) REFERENCES dbo.users(id),
    CONSTRAINT fk_staff_quote_room_type FOREIGN KEY(room_type_id) REFERENCES dbo.room_types(id),
    CONSTRAINT fk_staff_quote_reservation FOREIGN KEY(reservation_id) REFERENCES dbo.reservations(id),
    CONSTRAINT ck_staff_quote_quantity CHECK(quantity > 0),
    CONSTRAINT ck_staff_quote_guests CHECK(adults > 0 AND children >= 0),
    CONSTRAINT ck_staff_quote_amounts CHECK(base_price >= 0 AND total_amount >= 0 AND deposit_amount >= 0)
);

CREATE INDEX ix_staff_booking_quotes_expiry ON dbo.staff_booking_quotes(status, expires_at);
CREATE INDEX ix_staff_booking_quotes_hotel ON dbo.staff_booking_quotes(hotel_id, id);
