spring:
  application:
    name: backend



  datasource:
    # SQL Server Configuration
    url: jdbc:sqlserver://DESKTOP-JLPTS26:1433;databaseName=HotelDB;encrypt=false;trustServerCertificate=true
    username: sa
    password: HotelAdmin@2026!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 24 hours
  refresh-expiration: 604800000 # 7 days
